### PR TITLE
Add Catalog URL for Big Sur

### PR DESCRIPTION
**Pull request by karthikselva**

### CODE REVIEW

**Comment by MichalMMac** [comment]
I wonder what is the point of adding Big Sur catalog when we can't change the catalog URL on Big Sur clients. Keeping track of released updates using Reposado perhaps?

**Comment by gregneagle** [comment]
Thank you, but since you cannot point a Big Sur client to a reposado server I don't plan on making any changes/updates to reposado ever again. Of course if you still want to replicate the Big Sur sucatalog for some reason, you can always add the Big Sur sucatalog URL to your local preferences.plist.

**Comment by remixyz** [comment]
Setting the Catalog URL via Configuration Profile works, isnt it? I tried it and the Softwareupdate PrefPane showed up the updateserver.

**Comment by gregneagle** [comment]
Sure. But `softwareupdate` won't actually successfully _use_ the alternate catalog URL, complaining that its certificate doesn't meet its requirements.
If you have a way of getting `softwareupdate` in Big Sur to actually successfully use a non-Apple sucatalog, I'd love to see a full write-up.

**Comment by remixyz** [comment]
> Sure. But `softwareupdate` won't actually successfully _use_ the alternate catalog URL, complaining that its certificate doesn't meet its requirements.
> If you have a way of getting `softwareupdate` in Big Sur to actually successfully use a non-Apple sucatalog, I'd love to see a full write-up.

Oh ok, didnt tried it yet. Thank you 👍

**Pull request closed without merging**
