### PR TITLE
Manage deprecated products on a branch.

### PR DESCRIPTION
**Pull request by MagerValp**
I'm sharing a reposado server with someone who needs to keep deprecated products around, while I'm mainly interested in mirroring the latest Apple catalog. I'm too lazy to selectively add products, and adding all to my branch brings in all the deprecated products. Thus:

    repoutil --remove-product deprecated BRANCH
    repoutil --add-product non-deprecated BRANCH

This makes it easier to follow the current Apple catalog while still keeping deprecated products.

### CODE REVIEW

**Comment by MagerValp** [comment]
If you think that this is a good idea, I'll update the PR with docs and usage as well.

**Comment by gregneagle** [comment]
Yes. We can quibble over details later, but big picture it's fine.

**Comment by MagerValp** [comment]
I added a --non-deprecated list command, and updated the docs. Let me know if you want to quibble over any details.

**Comment by gregneagle** [comment]
Can you resolve the conflicts? I just merged another PR that is now causing this PR to have some conflicts.

**Comment by MagerValp** [comment]
Done. I also rearranged removal of deprecated products so that it doesn't print a lot of "is not in branch" warnings.

**Pull request merged**
